version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - app-storage:/var/www/storage
            - app-bootstrap:/var/www/bootstrap/cache
        depends_on:
            - db
        restart: unless-stopped
        networks:
            - laravel

    db:
        image: postgres:17
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - laravel

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app
        restart: unless-stopped
        networks:
            - laravel

networks:
    laravel:


volumes:
    app-storage:
    app-bootstrap:
    pgdata:
